import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "app/globals.css";
import Header from "app/common/Header";
import Footer from "app/common/Footer";
import Container from "app/common/Container";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-zinc-200 text-zinc-900 min-h-screen`}
      >
        <Container>
          <Header />
          {children}
          <Footer />
        </Container>
      </body>
    </html>
  );
}
